
name: Ionic & Cordova Build

on:
  push:
    branches: [ master, backend-integration, ci-test ]
  pull_request:
    branches: [ master, backend-integration, ci-test ]

jobs:
  android:
    name: Cordova Build Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node Modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Install Dependencies
      run: npm ci
      env:
        NG_CLI_ANALYTICS: ci
    - name: Run Ionic Build
      run: npx ionic build
    - name: Cordova Add Android
      run: npx ionic cordova platform add android
    - name: Copy google-service.json
      run: cp google-services.json platforms/android/app/
    - name: Cordova Build Android
      run: npx ionic cordova build android
    - name: Upload Debug APK
      uses: actions/upload-artifact@v1
      with:
        name: RIOD
        path: platforms/android/app/build/outputs/apk/debug/app-debug.apk

  ios:
    name: Cordova Build iOS
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache Node Modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Cache CocoaPods
      uses: actions/cache@v2
      env:
        cache-name: cache-cocoapods
      with:
        path: ~/Library/Caches/CocoaPods/Pods
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
    - name: Install Dependencies
      run: npm ci
      env:
        NG_CLI_ANALYTICS: ci
    - name: Run Ionic Build
      run: npx ionic build
    - name: Cordova Add iOS
      run: npx ionic cordova platform add ios
    - name: Cordova Build iOS
      run: npx ionic cordova build ios
